import Pkg

Pkg.add("ConfParser")
Pkg.add("Plots")
Pkg.add("PythonPlot")
Pkg.add("Printf")
Pkg.add("Flux")
Pkg.add("NNlib")
Pkg.add("CUDA")
Pkg.add("cuDNN")
Pkg.add("LinearAlgebra")
Pkg.add("KernelAbstractions")
Pkg.add("Tullio")
Pkg.add("MAT")
Pkg.add("Optim")
