import Pkg

Pkg.add("ConfParser")
Pkg.add("Plots")
Pkg.add("PythonPlot")
Pkg.add("Printf")
Pkg.add("Flux")
Pkg.add("NNlib")
Pkg.add("CUDA")
Pkg.add("cuDNN")
Pkg.add("LinearAlgebra")
Pkg.add("KernelAbstractions")
Pkg.add("Tullio")
Pkg.add("MAT")
Pkg.add("HyperTuning")
Pkg.add("CSV")
Pkg.add("ProgressBars")
Pkg.add("Optimisers")
Pkg.add("BSON")
Pkg.add("DataFrames")
Pkg.add("Statistics")
Pkg.add("PlotlyJS")
Pkg.add("Printf")